# CRM Access Governance & Customer Data Protection
## Stage 11 — AI Governance Extension

This notebook extends the project from **Data Governance** into **Data & AI Governance**.

The simulated scenario is:

> The organization introduces a Generative AI assistant connected to the CRM to help employees retrieve information, summarize customer history, draft responses, and support operational decisions.

The governance question becomes:

> How can the organization allow useful AI capabilities without bypassing existing access controls, exposing personal data, creating uncontrolled actions, or losing traceability?

### Main Goals

1. Define the AI use case and business purpose.
2. Create an AI system inventory.
3. Identify AI-specific risks.
4. Define data-access boundaries.
5. Ensure AI inherits CRM access controls.
6. Define PII and sensitive-data restrictions.
7. Define human oversight requirements.
8. Define prompt and response logging.
9. Define prohibited and restricted AI actions.
10. Create an AI Governance Control Catalog.
11. Create AI risk scoring and classification.
12. Define monitoring KPIs.
13. Map the project to NIST AI RMF concepts.
14. Prepare the project for final GitHub documentation and portfolio packaging.

> **Important:** this is a simulated governance exercise. The controls are project proposals and should not be treated as universal legal, regulatory, or security requirements.

In [1]:
# 1. Libraries and Settings

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 300)

print("Environment ready.")

Environment ready.

# 2. AI Use Case Definition

## Use Case

**CRM AI Assistant**

### Intended Capabilities

- summarize customer interaction history;
- answer employee questions about CRM records;
- assist with customer-service drafting;
- summarize account information;
- identify relevant CRM records;
- support operational analysis.

### Explicitly Excluded from Default Operation

- autonomous deletion of CRM records;
- autonomous bulk export of customer data;
- changing customer permissions;
- changing user permissions;
- sending external communications without human review;
- exposing direct customer identifiers to unauthorized users;
- bypassing the CRM access-control model.

# 3. AI System Inventory

AI systems should be treated as governed assets, not simply software features.

In [2]:
ai_system_inventory = pd.DataFrame([
    {
        "AI_System_ID": "AI-CRM-001",
        "System_Name": "CRM AI Assistant",
        "AI_Type": "Generative AI / LLM Assistant",
        "Business_Purpose": "Support CRM users with summarization, retrieval, drafting, and operational assistance.",
        "Business_Owner": "CRM Business Owner",
        "Technical_Owner": "AI / Data Engineering",
        "Risk_Owner": "Data & AI Governance Lead",
        "Data_Domains": "CRM Operations; Identity & Access; Customer Data",
        "Deployment_Status": "Simulated / Proposed",
        "Human_Oversight": "Required",
        "External_Action_Authority": "Restricted"
    }
])

display(ai_system_inventory)

,AI_System_ID,System_Name,AI_Type,Business_Purpose,Business_Owner,Technical_Owner,Risk_Owner,Data_Domains,Deployment_Status,Human_Oversight,External_Action_Authority
0,AI-CRM-001,CRM AI Assistant,Generative AI / LLM Assistant,"Support CRM users with summarization, retrieva...",CRM Business Owner,AI / Data Engineering,Data & AI Governance Lead,CRM Operations; Identity & Access; Customer Data,Simulated / Proposed,Required,Restricted

# 4. AI Actors and Responsibilities

The AI system introduces additional actors beyond the traditional data-governance model.

In [3]:
ai_actor_model = pd.DataFrame([
    ["Business Owner", "Defines approved AI purpose and accepts business risk."],
    ["AI Product Owner", "Maintains use-case scope, requirements, and operational performance."],
    ["Data & AI Governance Lead", "Maintains governance standards, risk classification, controls, and oversight."],
    ["Data Owner", "Approves use of governed data domains by the AI system."],
    ["Data Steward", "Maintains metadata, data quality, classification, and data-use context."],
    ["Information Security", "Reviews access controls, attack surfaces, logging, and security incidents."],
    ["Privacy / DPO", "Reviews personal-data use, minimization, exposure, and privacy risks."],
    ["AI / Data Engineering", "Implements model integration, guardrails, logging, retrieval, and monitoring."],
    ["End User", "Uses the AI assistant within approved purpose and access boundaries."],
    ["Human Reviewer", "Reviews outputs or actions when human oversight is required."]
], columns=["AI_Actor", "Responsibility"])

display(ai_actor_model)

,AI_Actor,Responsibility
0,Business Owner,Defines approved AI purpose and accepts busine...
1,AI Product Owner,"Maintains use-case scope, requirements, and op..."
2,Data & AI Governance Lead,"Maintains governance standards, risk classific..."
3,Data Owner,Approves use of governed data domains by the A...
4,Data Steward,"Maintains metadata, data quality, classificati..."
5,Information Security,"Reviews access controls, attack surfaces, logg..."
6,Privacy / DPO,"Reviews personal-data use, minimization, expos..."
7,AI / Data Engineering,"Implements model integration, guardrails, logg..."
8,End User,Uses the AI assistant within approved purpose ...
9,Human Reviewer,Reviews outputs or actions when human oversigh...

# 5. Existing Data Governance Controls Inherited by AI

The AI assistant should not create a parallel access model.

It should inherit the controls already defined in this project:

- role-based access;
- permission checks;
- data sensitivity;
- contextual risk;
- Data Quality monitoring;
- privacy classification;
- data minimization;
- lineage;
- stewardship;
- governance issue management.

This principle is summarized as:

> **AI access must not exceed the user's authorized data access.**

# 6. AI Data Access Architecture

```text
Employee
   |
   v
CRM AI Assistant
   |
   v
Identity + Role + Permission Check
   |
   v
Governance Policy Check
   |
   +------ BLOCK ------> Request Rejected
   |
   v
Approved Retrieval Scope
   |
   v
Privacy-Safe / Authorized CRM Data
   |
   v
LLM Processing
   |
   v
Output Guardrails
   |
   v
Human User
```

The AI assistant is positioned **inside** the governance boundary rather than bypassing it.

# 7. AI Risk Taxonomy

The project uses the following AI risk categories.

In [4]:
ai_risk_taxonomy = pd.DataFrame([
    ["AI-RISK-01", "Privacy Exposure", "AI output reveals direct identifiers or restricted customer information."],
    ["AI-RISK-02", "Unauthorized Data Access", "AI retrieves information outside the user's role or permission scope."],
    ["AI-RISK-03", "Hallucination / Incorrect Output", "AI generates inaccurate or unsupported CRM information."],
    ["AI-RISK-04", "Prompt Injection", "Malicious or manipulated content attempts to override AI instructions or controls."],
    ["AI-RISK-05", "Sensitive Data Leakage", "Confidential data appears in prompts, logs, responses, or external services."],
    ["AI-RISK-06", "Excessive Agency", "AI performs high-impact CRM actions without sufficient human control."],
    ["AI-RISK-07", "Insufficient Traceability", "Organization cannot reconstruct prompt, retrieved context, response, or decision path."],
    ["AI-RISK-08", "Poor Data Quality", "AI relies on incomplete, invalid, stale, or inconsistent CRM data."],
    ["AI-RISK-09", "Purpose Creep", "AI use expands beyond the approved business purpose."],
    ["AI-RISK-10", "Overreliance", "Users accept AI outputs without appropriate verification."],
    ["AI-RISK-11", "Inappropriate Retention", "Prompts, responses, or retrieved customer data are retained longer than intended."],
    ["AI-RISK-12", "Third-Party Exposure", "Customer or organizational data is unnecessarily shared with external AI services."]
], columns=["Risk_ID", "Risk_Category", "Risk_Description"])

display(ai_risk_taxonomy)

,Risk_ID,Risk_Category,Risk_Description
0,AI-RISK-01,Privacy Exposure,AI output reveals direct identifiers or restri...
1,AI-RISK-02,Unauthorized Data Access,AI retrieves information outside the user's ro...
2,AI-RISK-03,Hallucination / Incorrect Output,AI generates inaccurate or unsupported CRM inf...
3,AI-RISK-04,Prompt Injection,Malicious or manipulated content attempts to o...
4,AI-RISK-05,Sensitive Data Leakage,"Confidential data appears in prompts, logs, re..."
5,AI-RISK-06,Excessive Agency,AI performs high-impact CRM actions without su...
6,AI-RISK-07,Insufficient Traceability,"Organization cannot reconstruct prompt, retrie..."
7,AI-RISK-08,Poor Data Quality,"AI relies on incomplete, invalid, stale, or in..."
8,AI-RISK-09,Purpose Creep,AI use expands beyond the approved business pu...
9,AI-RISK-10,Overreliance,Users accept AI outputs without appropriate ve...
10,AI-RISK-11,Inappropriate Retention,"Prompts, responses, or retrieved customer data..."
11,AI-RISK-12,Third-Party Exposure,Customer or organizational data is unnecessari...

# 8. AI Risk Assessment Model

For the portfolio prototype, each risk is assessed using:

- Likelihood: 1–5
- Impact: 1–5
- Risk Score = Likelihood × Impact

Proposed interpretation:

- 1–4 → LOW
- 5–9 → MEDIUM
- 10–15 → HIGH
- 16–25 → CRITICAL

In [5]:
ai_risk_register = pd.DataFrame([
    ["AI-RISK-01", 3, 5],
    ["AI-RISK-02", 3, 5],
    ["AI-RISK-03", 4, 4],
    ["AI-RISK-04", 3, 4],
    ["AI-RISK-05", 3, 5],
    ["AI-RISK-06", 2, 5],
    ["AI-RISK-07", 3, 4],
    ["AI-RISK-08", 3, 4],
    ["AI-RISK-09", 2, 4],
    ["AI-RISK-10", 4, 3],
    ["AI-RISK-11", 2, 4],
    ["AI-RISK-12", 2, 5]
], columns=["Risk_ID", "Likelihood", "Impact"])

ai_risk_register["Risk_Score"] = (
    ai_risk_register["Likelihood"] *
    ai_risk_register["Impact"]
)

def classify_ai_risk(score):
    if score <= 4:
        return "LOW"
    elif score <= 9:
        return "MEDIUM"
    elif score <= 15:
        return "HIGH"
    return "CRITICAL"

ai_risk_register["Risk_Level"] = (
    ai_risk_register["Risk_Score"]
    .apply(classify_ai_risk)
)

ai_risk_register = ai_risk_register.merge(
    ai_risk_taxonomy,
    on="Risk_ID",
    how="left"
)

display(
    ai_risk_register[
        [
            "Risk_ID",
            "Risk_Category",
            "Likelihood",
            "Impact",
            "Risk_Score",
            "Risk_Level"
        ]
    ].sort_values("Risk_Score", ascending=False)
)

,Risk_ID,Risk_Category,Likelihood,Impact,Risk_Score,Risk_Level
2,AI-RISK-03,Hallucination / Incorrect Output,4,4,16,CRITICAL
0,AI-RISK-01,Privacy Exposure,3,5,15,HIGH
1,AI-RISK-02,Unauthorized Data Access,3,5,15,HIGH
4,AI-RISK-05,Sensitive Data Leakage,3,5,15,HIGH
3,AI-RISK-04,Prompt Injection,3,4,12,HIGH
6,AI-RISK-07,Insufficient Traceability,3,4,12,HIGH
7,AI-RISK-08,Poor Data Quality,3,4,12,HIGH
9,AI-RISK-10,Overreliance,4,3,12,HIGH
5,AI-RISK-06,Excessive Agency,2,5,10,HIGH
11,AI-RISK-12,Third-Party Exposure,2,5,10,HIGH
8,AI-RISK-09,Purpose Creep,2,4,8,MEDIUM
10,AI-RISK-11,Inappropriate Retention,2,4,8,MEDIUM

# 9. AI Governance Control Catalog

Each AI control receives a stable identifier to support auditability and lineage.

In [6]:
ai_control_catalog = pd.DataFrame([
    ["AI-CTRL-001", "Access Control", "AI assistant must inherit the authenticated user's CRM role and permissions.", "Prevent unauthorized data access.", "AI-RISK-02", "Preventive"],
    ["AI-CTRL-002", "Privacy", "Direct identifiers must not be exposed unless required by an approved use case and authorized role.", "Reduce privacy exposure.", "AI-RISK-01; AI-RISK-05", "Preventive"],
    ["AI-CTRL-003", "Data Minimization", "Only data required for the user request may be retrieved for AI processing.", "Reduce unnecessary data exposure.", "AI-RISK-01; AI-RISK-05; AI-RISK-12", "Preventive"],
    ["AI-CTRL-004", "Human Oversight", "High-impact or external actions require human review before execution.", "Limit excessive agency.", "AI-RISK-06; AI-RISK-10", "Preventive"],
    ["AI-CTRL-005", "Logging", "Prompt, user, retrieved context references, response, and control outcome must be logged.", "Enable traceability and investigation.", "AI-RISK-07", "Detective"],
    ["AI-CTRL-006", "Output Validation", "AI-generated factual CRM summaries should identify source records or supporting context where feasible.", "Reduce unsupported output risk.", "AI-RISK-03", "Preventive / Detective"],
    ["AI-CTRL-007", "Prompt Security", "Retrieved content and user prompts must be treated as untrusted input and subject to prompt-injection controls.", "Reduce instruction manipulation.", "AI-RISK-04", "Preventive"],
    ["AI-CTRL-008", "Data Quality", "AI retrieval should use governed data that passes defined Data Quality controls.", "Reduce poor-data-driven output.", "AI-RISK-08", "Preventive"],
    ["AI-CTRL-009", "Purpose Limitation", "AI use must remain within the approved CRM assistant use case.", "Prevent uncontrolled use expansion.", "AI-RISK-09", "Preventive"],
    ["AI-CTRL-010", "Retention", "Prompt and response retention must follow documented retention requirements.", "Reduce unnecessary retained sensitive data.", "AI-RISK-11", "Preventive"],
    ["AI-CTRL-011", "Third-Party Governance", "External AI services must receive only approved and minimized data.", "Reduce third-party exposure.", "AI-RISK-12", "Preventive"],
    ["AI-CTRL-012", "User Transparency", "Users should be informed that the response is AI-generated and may require verification.", "Reduce overreliance.", "AI-RISK-03; AI-RISK-10", "Preventive"],
    ["AI-CTRL-013", "Action Restriction", "Bulk export, deletion, permission changes, and other high-impact actions are disabled by default.", "Prevent excessive agency and high-impact mistakes.", "AI-RISK-06", "Preventive"],
    ["AI-CTRL-014", "Incident Management", "AI incidents must enter the existing governance issue and escalation workflow.", "Integrate AI risk into governance operations.", "Multiple", "Corrective"]
], columns=[
    "Control_ID",
    "Control_Domain",
    "Control_Description",
    "Objective",
    "Related_Risk_ID",
    "Control_Type"
])

display(ai_control_catalog)

,Control_ID,Control_Domain,Control_Description,Objective,Related_Risk_ID,Control_Type
0,AI-CTRL-001,Access Control,AI assistant must inherit the authenticated us...,Prevent unauthorized data access.,AI-RISK-02,Preventive
1,AI-CTRL-002,Privacy,Direct identifiers must not be exposed unless ...,Reduce privacy exposure.,AI-RISK-01; AI-RISK-05,Preventive
2,AI-CTRL-003,Data Minimization,Only data required for the user request may be...,Reduce unnecessary data exposure.,AI-RISK-01; AI-RISK-05; AI-RISK-12,Preventive
3,AI-CTRL-004,Human Oversight,High-impact or external actions require human ...,Limit excessive agency.,AI-RISK-06; AI-RISK-10,Preventive
4,AI-CTRL-005,Logging,"Prompt, user, retrieved context references, re...",Enable traceability and investigation.,AI-RISK-07,Detective
5,AI-CTRL-006,Output Validation,AI-generated factual CRM summaries should iden...,Reduce unsupported output risk.,AI-RISK-03,Preventive / Detective
6,AI-CTRL-007,Prompt Security,Retrieved content and user prompts must be tre...,Reduce instruction manipulation.,AI-RISK-04,Preventive
7,AI-CTRL-008,Data Quality,AI retrieval should use governed data that pas...,Reduce poor-data-driven output.,AI-RISK-08,Preventive
8,AI-CTRL-009,Purpose Limitation,AI use must remain within the approved CRM ass...,Prevent uncontrolled use expansion.,AI-RISK-09,Preventive
9,AI-CTRL-010,Retention,Prompt and response retention must follow docu...,Reduce unnecessary retained sensitive data.,AI-RISK-11,Preventive
10,AI-CTRL-011,Third-Party Governance,External AI services must receive only approve...,Reduce third-party exposure.,AI-RISK-12,Preventive
11,AI-CTRL-012,User Transparency,Users should be informed that the response is ...,Reduce overreliance.,AI-RISK-03; AI-RISK-10,Preventive
12,AI-CTRL-013,Action Restriction,"Bulk export, deletion, permission changes, and...",Prevent excessive agency and high-impact mista...,AI-RISK-06,Preventive
13,AI-CTRL-014,Incident Management,AI incidents must enter the existing governanc...,Integrate AI risk into governance operations.,Multiple,Corrective

# 10. AI Action Classification

AI capabilities are classified by required oversight.

In [7]:
ai_action_matrix = pd.DataFrame([
    ["Search authorized CRM records", "ALLOW", "Standard logging"],
    ["Summarize authorized CRM records", "ALLOW", "Source/context traceability"],
    ["Draft internal note", "ALLOW", "User review"],
    ["Draft customer response", "REVIEW", "Human approval before sending"],
    ["Retrieve direct customer identifier", "REVIEW", "Role + purpose check"],
    ["Access high-sensitivity customer data", "REVIEW", "Enhanced authorization"],
    ["Export CRM records", "BLOCK", "Not allowed autonomously"],
    ["Delete CRM record", "BLOCK", "Not allowed autonomously"],
    ["Change user permission", "BLOCK", "Not allowed"],
    ["Change CRM role", "BLOCK", "Not allowed"],
    ["Send external communication", "REVIEW", "Human approval required"],
    ["Execute financial approval", "BLOCK", "Outside approved AI scope"]
], columns=[
    "AI_Action",
    "Default_AI_Decision",
    "Required_Control"
])

display(ai_action_matrix)

,AI_Action,Default_AI_Decision,Required_Control
0,Search authorized CRM records,ALLOW,Standard logging
1,Summarize authorized CRM records,ALLOW,Source/context traceability
2,Draft internal note,ALLOW,User review
3,Draft customer response,REVIEW,Human approval before sending
4,Retrieve direct customer identifier,REVIEW,Role + purpose check
5,Access high-sensitivity customer data,REVIEW,Enhanced authorization
6,Export CRM records,BLOCK,Not allowed autonomously
7,Delete CRM record,BLOCK,Not allowed autonomously
8,Change user permission,BLOCK,Not allowed
9,Change CRM role,BLOCK,Not allowed
10,Send external communication,REVIEW,Human approval required
11,Execute financial approval,BLOCK,Outside approved AI scope

# 11. Data Classification for AI Use

The AI assistant should consume different data classes differently.

In [8]:
ai_data_access_policy = pd.DataFrame([
    ["Internal", "Allowed", "Normal authorization and logging"],
    ["Confidential", "Conditional", "Role authorization + minimized retrieval"],
    ["Restricted", "Highly Restricted", "Explicit business need + authorization + logging"],
    ["Direct Identifier", "Highly Restricted", "Purpose-specific access only"],
    ["Analytics-Safe Customer Data", "Preferred", "Use when direct identity is unnecessary"],
    ["Masked Data", "Preferred", "Use for operational display when full value is unnecessary"]
], columns=[
    "Data_Class",
    "AI_Access_Level",
    "Control_Expectation"
])

display(ai_data_access_policy)

,Data_Class,AI_Access_Level,Control_Expectation
0,Internal,Allowed,Normal authorization and logging
1,Confidential,Conditional,Role authorization + minimized retrieval
2,Restricted,Highly Restricted,Explicit business need + authorization + logging
3,Direct Identifier,Highly Restricted,Purpose-specific access only
4,Analytics-Safe Customer Data,Preferred,Use when direct identity is unnecessary
5,Masked Data,Preferred,Use for operational display when full value is...

# 12. Prompt and Response Logging Schema

Traceability requires more than storing the final answer.

In [9]:
ai_log_schema = pd.DataFrame([
    ["Interaction_ID", "Unique AI interaction identifier"],
    ["Timestamp", "Interaction date and time"],
    ["User_ID", "Authenticated CRM user"],
    ["Role", "User role"],
    ["Use_Case_ID", "Approved AI use case"],
    ["Prompt_Category", "High-level prompt classification"],
    ["Retrieved_Record_References", "References to CRM records used as context"],
    ["Sensitivity_Level", "Highest sensitivity level in retrieved context"],
    ["Permission_Check_Result", "Pass / Fail"],
    ["Governance_Check_Result", "Pass / Review / Block"],
    ["AI_Model_ID", "Model or deployment identifier"],
    ["Response_ID", "Generated-response identifier"],
    ["Human_Review_Required", "Boolean oversight flag"],
    ["Human_Review_Result", "Approved / Rejected / Modified / Not Required"],
    ["Triggered_AI_Control", "Control responsible for intervention"],
    ["Incident_Flag", "Whether interaction created an AI governance incident"]
], columns=["Log_Field", "Description"])

display(ai_log_schema)

,Log_Field,Description
0,Interaction_ID,Unique AI interaction identifier
1,Timestamp,Interaction date and time
2,User_ID,Authenticated CRM user
3,Role,User role
4,Use_Case_ID,Approved AI use case
5,Prompt_Category,High-level prompt classification
6,Retrieved_Record_References,References to CRM records used as context
7,Sensitivity_Level,Highest sensitivity level in retrieved context
8,Permission_Check_Result,Pass / Fail
9,Governance_Check_Result,Pass / Review / Block
10,AI_Model_ID,Model or deployment identifier
11,Response_ID,Generated-response identifier
12,Human_Review_Required,Boolean oversight flag
13,Human_Review_Result,Approved / Rejected / Modified / Not Required
14,Triggered_AI_Control,Control responsible for intervention
15,Incident_Flag,Whether interaction created an AI governance i...

# 13. Human Oversight Model

Human oversight should increase with risk and action impact.

| Situation | Oversight |
|---|---|
| Simple authorized retrieval | Normal user verification |
| Internal summary | User review |
| Customer-facing draft | Mandatory human approval |
| High-sensitivity access | Enhanced review |
| External action | Mandatory approval |
| High-impact autonomous action | Prohibited by default |

# 14. AI Incident Categories

In [10]:
ai_incident_categories = pd.DataFrame([
    ["AI-INC-01", "Privacy Exposure", "AI response exposed restricted or personal information improperly."],
    ["AI-INC-02", "Access Control Failure", "AI accessed information outside authorized scope."],
    ["AI-INC-03", "Incorrect Critical Output", "Materially incorrect AI output affected or could affect a business decision."],
    ["AI-INC-04", "Prompt Injection", "Prompt or retrieved content attempted to manipulate system behavior."],
    ["AI-INC-05", "Unauthorized Action", "AI attempted or executed an action outside approved authority."],
    ["AI-INC-06", "Logging Failure", "Required interaction traceability was unavailable."],
    ["AI-INC-07", "Purpose Violation", "AI used outside the approved business purpose."],
    ["AI-INC-08", "Third-Party Data Exposure", "Data was improperly shared with an external AI service."]
], columns=[
    "Incident_ID",
    "Incident_Category",
    "Description"
])

display(ai_incident_categories)

,Incident_ID,Incident_Category,Description
0,AI-INC-01,Privacy Exposure,AI response exposed restricted or personal inf...
1,AI-INC-02,Access Control Failure,AI accessed information outside authorized scope.
2,AI-INC-03,Incorrect Critical Output,Materially incorrect AI output affected or cou...
3,AI-INC-04,Prompt Injection,Prompt or retrieved content attempted to manip...
4,AI-INC-05,Unauthorized Action,AI attempted or executed an action outside app...
5,AI-INC-06,Logging Failure,Required interaction traceability was unavaila...
6,AI-INC-07,Purpose Violation,AI used outside the approved business purpose.
7,AI-INC-08,Third-Party Data Exposure,Data was improperly shared with an external AI...

# 15. AI Governance Decision Logic

A simplified decision path:

```text
AI Request
   |
   v
Approved Use Case?
   |
 NO ---> BLOCK
   |
 YES
   |
   v
User Authorized for Requested Data?
   |
 NO ---> BLOCK
   |
 YES
   |
   v
Sensitive / Restricted Data?
   |
 YES ---> Enhanced Controls / REVIEW
   |
   v
High-Impact Action?
   |
 YES ---> Human Approval or BLOCK
   |
   v
AI Processing
   |
   v
Output Validation + Logging
   |
   v
User
```

# 16. AI Governance RACI

In [11]:
ai_raci = pd.DataFrame([
    ["Approve AI use case", "AI Product Owner", "CRM Business Owner", "Data & AI Governance + Security + Privacy", "End Users"],
    ["Approve CRM data use by AI", "Data Steward", "Data Owner", "Privacy + Security", "AI Engineering"],
    ["Maintain AI risk register", "Data & AI Governance Lead", "CRM Business Owner", "Security + Privacy + AI Engineering", "Governance Committee"],
    ["Implement AI controls", "AI / Data Engineering", "AI Product Owner", "Security + Data Governance", "Data Owner"],
    ["Approve high-risk exception", "Data & AI Governance Lead", "Governance Committee", "Security + Privacy + Data Owner", "AI Product Owner"],
    ["Investigate AI incident", "AI / Data Engineering", "Data & AI Governance Lead", "Security + Privacy", "CRM Business Owner"],
    ["Review AI performance", "AI Product Owner", "CRM Business Owner", "AI Engineering + Data Governance", "Governance Committee"],
    ["Review privacy impact", "Privacy Data Steward", "Privacy / DPO", "Security + Data Owner", "AI Product Owner"]
], columns=[
    "Activity",
    "Responsible",
    "Accountable",
    "Consulted",
    "Informed"
])

display(ai_raci)

,Activity,Responsible,Accountable,Consulted,Informed
0,Approve AI use case,AI Product Owner,CRM Business Owner,Data & AI Governance + Security + Privacy,End Users
1,Approve CRM data use by AI,Data Steward,Data Owner,Privacy + Security,AI Engineering
2,Maintain AI risk register,Data & AI Governance Lead,CRM Business Owner,Security + Privacy + AI Engineering,Governance Committee
3,Implement AI controls,AI / Data Engineering,AI Product Owner,Security + Data Governance,Data Owner
4,Approve high-risk exception,Data & AI Governance Lead,Governance Committee,Security + Privacy + Data Owner,AI Product Owner
5,Investigate AI incident,AI / Data Engineering,Data & AI Governance Lead,Security + Privacy,CRM Business Owner
6,Review AI performance,AI Product Owner,CRM Business Owner,AI Engineering + Data Governance,Governance Committee
7,Review privacy impact,Privacy Data Steward,Privacy / DPO,Security + Data Owner,AI Product Owner

# 17. AI Governance Review Cadence

In [12]:
ai_review_cadence = pd.DataFrame([
    ["AI Interaction Monitoring", "Weekly", "AI Product Owner + Governance Analyst"],
    ["AI Incident Review", "Weekly / Event-driven", "AI Governance + Security + Privacy"],
    ["AI Risk Register", "Monthly", "Data & AI Governance Lead"],
    ["Access and Privacy Controls", "Monthly", "Security + Privacy + Data Governance"],
    ["AI Use Case Scope", "Quarterly", "CRM Business Owner"],
    ["Model / Deployment Review", "Quarterly or Change-driven", "AI Engineering + Governance"],
    ["AI Governance Committee Review", "Quarterly", "Governance Committee"]
], columns=[
    "Governance_Activity",
    "Cadence",
    "Primary_Participants"
])

display(ai_review_cadence)

,Governance_Activity,Cadence,Primary_Participants
0,AI Interaction Monitoring,Weekly,AI Product Owner + Governance Analyst
1,AI Incident Review,Weekly / Event-driven,AI Governance + Security + Privacy
2,AI Risk Register,Monthly,Data & AI Governance Lead
3,Access and Privacy Controls,Monthly,Security + Privacy + Data Governance
4,AI Use Case Scope,Quarterly,CRM Business Owner
5,Model / Deployment Review,Quarterly or Change-driven,AI Engineering + Governance
6,AI Governance Committee Review,Quarterly,Governance Committee

# 18. AI Governance KPIs

The future governance dashboard can monitor AI-specific controls.

In [13]:
ai_governance_kpis = pd.DataFrame([
    ["AI-KPI-001", "AI Interactions", "Total governed AI interactions."],
    ["AI-KPI-002", "Blocked AI Requests", "Requests blocked by access or governance controls."],
    ["AI-KPI-003", "AI Requests Under Review", "Requests requiring human or governance review."],
    ["AI-KPI-004", "High-Risk AI Interactions", "Interactions classified as high or critical risk."],
    ["AI-KPI-005", "Sensitive Data Retrieval Rate", "Share of AI requests involving restricted data."],
    ["AI-KPI-006", "Human Review Rate", "Share of AI interactions requiring human approval."],
    ["AI-KPI-007", "AI Incident Count", "Recorded AI governance incidents."],
    ["AI-KPI-008", "Access Control Violations", "Attempts to access data outside authorized scope."],
    ["AI-KPI-009", "Privacy Control Interventions", "Interactions where privacy controls changed or blocked processing."],
    ["AI-KPI-010", "AI Logging Coverage %", "Share of AI interactions with complete traceability logs."],
    ["AI-KPI-011", "AI Control Coverage %", "Share of identified risks with mapped controls."],
    ["AI-KPI-012", "Open High-Risk AI Issues", "Unresolved high-risk AI governance issues."]
], columns=[
    "KPI_ID",
    "KPI_Name",
    "Definition"
])

display(ai_governance_kpis)

,KPI_ID,KPI_Name,Definition
0,AI-KPI-001,AI Interactions,Total governed AI interactions.
1,AI-KPI-002,Blocked AI Requests,Requests blocked by access or governance contr...
2,AI-KPI-003,AI Requests Under Review,Requests requiring human or governance review.
3,AI-KPI-004,High-Risk AI Interactions,Interactions classified as high or critical risk.
4,AI-KPI-005,Sensitive Data Retrieval Rate,Share of AI requests involving restricted data.
5,AI-KPI-006,Human Review Rate,Share of AI interactions requiring human appro...
6,AI-KPI-007,AI Incident Count,Recorded AI governance incidents.
7,AI-KPI-008,Access Control Violations,Attempts to access data outside authorized scope.
8,AI-KPI-009,Privacy Control Interventions,Interactions where privacy controls changed or...
9,AI-KPI-010,AI Logging Coverage %,Share of AI interactions with complete traceab...
10,AI-KPI-011,AI Control Coverage %,Share of identified risks with mapped controls.
11,AI-KPI-012,Open High-Risk AI Issues,Unresolved high-risk AI governance issues.

# 19. Risk-to-Control Coverage

This check verifies whether identified AI risks have at least one mapped control.

In [14]:
risk_ids = set(ai_risk_taxonomy["Risk_ID"])

mapped_risks = set()

for value in ai_control_catalog["Related_Risk_ID"]:
    for risk_id in risk_ids:
        if risk_id in value:
            mapped_risks.add(risk_id)

coverage = (
    len(mapped_risks) /
    len(risk_ids) *
    100
)

risk_control_coverage = pd.DataFrame({
    "Metric": [
        "Identified AI Risks",
        "Risks with Mapped Controls",
        "Risk-to-Control Coverage %"
    ],
    "Value": [
        len(risk_ids),
        len(mapped_risks),
        coverage
    ]
})

display(risk_control_coverage.round(2))

                       Metric  Value
0         Identified AI Risks   12.0
1  Risks with Mapped Controls   12.0
2  Risk-to-Control Coverage %  100.0

# 20. NIST AI RMF Mapping

This project uses the NIST AI Risk Management Framework as a **conceptual reference**, not as a formal certification claim.

The AI RMF Core is organized around four functions:

### GOVERN
Establish governance structure, responsibilities, policies, and accountability.

Project examples:
- AI system inventory;
- AI RACI;
- governance control catalog;
- review cadence;
- ownership.

### MAP
Understand the AI context, use case, affected data, users, and potential impacts.

Project examples:
- CRM AI use-case definition;
- data-access architecture;
- AI risk taxonomy;
- actor model;
- action classification.

### MEASURE
Assess and monitor AI risk.

Project examples:
- likelihood × impact scoring;
- risk levels;
- control coverage;
- AI governance KPIs;
- incident categories.

### MANAGE
Prioritize and respond to AI risks.

Project examples:
- BLOCK / REVIEW / ALLOW logic;
- human oversight;
- incident management;
- action restrictions;
- policy exceptions;
- remediation and escalation.

In [15]:
nist_mapping = pd.DataFrame([
    ["GOVERN", "AI inventory, RACI, control catalog, ownership, review cadence"],
    ["MAP", "Use case, actors, data access, risk taxonomy, action classification"],
    ["MEASURE", "Risk scoring, control coverage, monitoring KPIs, incidents"],
    ["MANAGE", "Access decisions, human review, blocked actions, incident response"]
], columns=[
    "NIST_AI_RMF_Function",
    "Project_Implementation"
])

display(nist_mapping)

  NIST_AI_RMF_Function                             Project_Implementation
0               GOVERN  AI inventory, RACI, control catalog, ownership...
1                  MAP  Use case, actors, data access, risk taxonomy, ...
2              MEASURE  Risk scoring, control coverage, monitoring KPI...
3               MANAGE  Access decisions, human review, blocked action...

# 21. Generative AI-Specific Governance Considerations

Because the simulated CRM assistant uses Generative AI, additional concerns include:

- prompt injection;
- inaccurate or fabricated responses;
- sensitive information disclosure;
- overreliance on generated output;
- uncontrolled agency;
- prompt/response retention;
- third-party model exposure;
- traceability of retrieved context and generated output.

These concerns are incorporated into the risk and control catalogs above.

# 22. AI Governance Architecture

```text
DATA GOVERNANCE FOUNDATION
        |
        +--> Data Quality
        +--> Metadata
        +--> Classification
        +--> Privacy
        +--> Access Control
        +--> Lineage
        +--> Stewardship
        |
        v
AI USE CASE
        |
        v
AI RISK ASSESSMENT
        |
        v
AI GOVERNANCE CONTROLS
        |
        +--> Access Guardrails
        +--> Privacy Guardrails
        +--> Human Oversight
        +--> Logging
        +--> Output Validation
        +--> Incident Management
        |
        v
GOVERNED CRM AI ASSISTANT
```

# 23. Exportable AI Governance Artifacts

The following DataFrames are intended to become persistent project artifacts:

- `ai_system_inventory`
- `ai_actor_model`
- `ai_risk_taxonomy`
- `ai_risk_register`
- `ai_control_catalog`
- `ai_action_matrix`
- `ai_data_access_policy`
- `ai_log_schema`
- `ai_incident_categories`
- `ai_raci`
- `ai_review_cadence`
- `ai_governance_kpis`
- `nist_mapping`

Suggested GitHub structure:

```text
governance/
└── ai_governance/
    ├── ai_system_inventory.csv
    ├── ai_risk_register.csv
    ├── ai_control_catalog.csv
    ├── ai_action_matrix.csv
    ├── ai_logging_schema.csv
    ├── ai_incident_categories.csv
    ├── ai_raci.csv
    └── nist_ai_rmf_mapping.csv
```

# 24. Findings to Document

## AI Use Case
- Approved purpose:
- Prohibited capabilities:
- Human oversight requirement:

## Risk Assessment
- Highest-risk categories:
- Critical risks:
- High risks:

## Controls
- Total controls:
- Risk-to-control coverage:
- Preventive controls:
- Detective controls:

## Data Governance Integration
- Existing governance controls inherited by AI:
- Privacy-safe data preference:
- Access model:

## Monitoring
- Priority KPIs:
- Incident escalation path:
- Review cadence:

## AI Governance Conclusions
1.
2.
3.

# 25. Limitations

1. The AI assistant is simulated.
2. No production LLM or AI service is connected.
3. Risk scores are project assumptions.
4. Controls are governance proposals, not universal requirements.
5. No formal AI impact assessment is performed.
6. No model evaluation dataset is included.
7. No adversarial testing or red-team exercise is performed.
8. No real prompt logs exist.
9. No legal compliance claim is made.
10. NIST AI RMF is used as a conceptual governance reference rather than a certification framework.

# 26. References

Primary governance references used in this stage:

- **NIST AI Risk Management Framework (AI RMF 1.0)** — NIST AI 100-1, January 2023.
- **Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile** — NIST AI 600-1, July 2024.
- **NIST AI Resource Center / AI RMF Playbook** — implementation resources supporting operationalization of the AI RMF.

Note: NIST indicates that AI RMF 1.0 is currently being revised. This notebook therefore treats the framework as a current conceptual reference and avoids claiming formal alignment or certification.

# 27. Next Step — GitHub Documentation & Final Packaging

## Stage 12 — GitHub Documentation & Final Packaging

Planned outputs:

- final repository structure;
- README;
- project architecture;
- business problem;
- governance framework summary;
- notebook index;
- artifact inventory;
- project methodology;
- key findings;
- Power BI section;
- Data & AI Governance positioning;
- limitations;
- skills demonstrated;
- portfolio-ready project description.

This final stage will convert the technical work into a clear professional portfolio project.